-- Find total customers by country 
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(gender) AS total_customers_gender 
FROM gold.dim_customers 
GROUP BY gender
ORDER BY total_customers_gender DESC;

-- Find total products by category 
SELECT category, COUNT(DISTINCT product_name) AS total_products_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_products_category DESC;

-- What is the average cost in each category?
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
p.category, 
SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category 
ORDER BY total_revenue DESC;

-- Find the total revenue generated by each customer 
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries? 
SELECT 
c.country,
SUM(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_quantity DESC;

-- Which 5 products generated the highest revenue? 
SELECT TOP 5
p.product_name, 
SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

SELECT * FROM (
	SELECT 
	p.product_name, 
	SUM(f.sales) AS total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON f.product_key = p.product_key
	GROUP BY p.product_name)t 
WHERE rank_products <= 5

-- What are the 5 worst-performing products in sales? 
SELECT TOP 5
p.product_name, 
SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

-- Find the top 10 customers who have generated the highest revenue 
SELECT TOP 10
c.customer_key,
c.first_name, 
c.last_name,
SUM(s.sales) AS total_sales 
FROM gold.dim_customers c 
LEFT JOIN gold.fact_sales s
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name, 
c.last_name

-- Lowest 3 orders placed 
SELECT TOP 3
c.customer_key,
c.first_name, 
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.dim_customers c 
LEFT JOIN gold.fact_sales s
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name, 
c.last_name
ORDER BY total_orders 